version: '3'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    container_name: django
    build: .
    restart: always
    env_file:
      - django.env
      - postgres.env
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - postgres

volumes:
  pgdata: