version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    container_name: django
    build: .
    env_file:
      - django.env
      - postgres.env
    command:
      - /bin/sh
      - -c
      - |
        # echo "DROP DATABASE [IF EXISTS] unicamp | psql"
        ./manage.py makemigrations subjects
        ./manage.py migrate
        ./manage.py test subjects/tests/
        ./manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - postgres

volumes:
  pgdata: