version: '3'

services:
  db:
    container_name: db
    image: postgres
    env_file:
      - postgres.env
  web:
    container_name: django
    build: .
    env_file:
      - django.env
    command:
      - /bin/sh
      - -c
      - |
        ./manage.py makemigrations
        ./manage.py migrate
        ./manage.py test subjects/tests/
        ./manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db