version: "3.7"

services:
  postgres:
    image: postgres
    restart: always
    container_name: db
    env_file:
      - env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  api:
    container_name: api
    build: .
    restart: always
    env_file:
      - env/django.env
      - env/postgres.env
    command: python3 manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  pgdata:
