version: '3'

services:
  db:
    container_name: db
    image: postgres
    env_file:
      - postgres.env
  web:
    container_name: web
    build: .
    env_file:
      - django.env
    command: bash -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db