from subjects.models import Semester, Subject, PreReq, Continence, Equivalence
from institutes.models import Institute
from api.utils import json_to_data, string_to_int


def store_subjects(path):
    """
    Gets subjects data from subjects.json (generated by web scraping)
    and instantiates Subject objects in the database
    """
    subjects_data = json_to_data(path)
    subjects = subjects_data["subjects"]

    for subject in subjects:
        institute_instance = Institute.objects.get(
            initials=subject["institute"])
        try:
            semester_instance = Semester.objects.get(
                year=subject["semester"]["year"],
                semester=subject["semester"]["semester"])
        except:
            semester_instance = Semester(
                year=subject["semester"]["year"],
                semester=subject["semester"]["semester"])

        semester_instance.save()
        subject_instance = Subject(initials=subject["initials"],
                                   name=subject["name"],
                                   syllabus=subject["syllabus"],
                                   workload=string_to_int(subject["workload"]),
                                   institute=institute_instance)
        subject_instance.save()
        semester_instance.subjects.add(subject_instance)

        for pre_req_obj in subject["pre_reqs"]:
            for pre_req in pre_req_obj["pre_reqs"]:
                if pre_req != "":
                    try:
                        pre_req_instance = PreReq.objects.get(
                            initials=str(pre_req),
                            year_start=pre_req_obj["year_start"],
                            year_end=pre_req_obj["year_end"])
                    except:
                        pre_req_instance = PreReq(
                            initials=str(pre_req),
                            year_start=pre_req_obj["year_start"],
                            year_end=pre_req_obj["year_end"])
                        pre_req_instance.save()
                    subject_instance.prereqs.add(pre_req_instance)

            for cont_elem in subject["continencies"]:
                if cont_elem != "":
                    try:
                        continence = Continence.objects.get(
                            initials=str(cont_elem))
                    except:
                        continence = Continence(initials=str(cont_elem))
                        continence.save()
                    subject_instance.continences.add(continence)

            for equiv_elem in subject["equivalencies"]:
                if equiv_elem != "":
                    try:
                        equivalence = Equivalence.objects.get(
                            initials=str(equiv_elem))
                    except:
                        equivalence = Equivalence(initials=str(equiv_elem))
                        equivalence.save()
                    subject_instance.equivalences.add(equivalence)


def run():
    store_subjects("subjects/subjects.json")
